#
#  ________  ________  ________  ________  _______   ________  ________  ________  ________  ________
# |\   ____\|\   ____\|\   __  \|\   __  \|\  ___ \ |\   __  \|\   __  \|\   __  \|\   __  \|\   ___ \
# \ \  \___|\ \  \___|\ \  \|\  \ \  \|\  \ \   __/|\ \  \|\ /\ \  \|\  \ \  \|\  \ \  \|\  \ \  \_|\ \
#  \ \_____  \ \  \    \ \  \\\  \ \   _  _\ \  \_|/_\ \   __  \ \  \\\  \ \   __  \ \   _  _\ \  \ \\ \
#   \|____|\  \ \  \____\ \  \\\  \ \  \\  \\ \  \_|\ \ \  \|\  \ \  \\\  \ \  \ \  \ \  \\  \\ \  \_\\ \
#    ____\_\  \ \_______\ \_______\ \__\\ _\\ \_______\ \_______\ \_______\ \__\ \__\ \__\\ _\\ \_______\
#    |\_________\|_______|\|_______|\|__|\|__|\|_______|\|_______|\|_______|\|__|\|__|\|__|\|__|\|_______|
#   \|_________|


settings:
  # What should be the default scoreboard?
  default-scoreboard: 'default'
  # Should we disable Scoreboard in certain worlds?
  disabled-worlds:
    - '1234'

hooks:
   # To what plugins should we hook into?
   placeholderapi: true
   mvdwplaceholderapi: true